all_movies = [
    # Marvel Cinematic Universe (37 films)
    "Iron Man", "The Incredible Hulk", "Iron Man 2", "Thor",
    "Captain America: The First Avenger", "The Avengers", "Iron Man 3",
    "Thor: The Dark World", "Captain America: The Winter Soldier",
    "Guardians of the Galaxy", "Avengers: Age of Ultron", "Ant-Man",
    "Captain America: Civil War", "Doctor Strange", "Guardians of the Galaxy Vol. 2",
    "Spider-Man: Homecoming", "Thor: Ragnarok", "Black Panther",
    "Avengers: Infinity War", "Ant-Man and the Wasp", "Captain Marvel",
    "Avengers: Endgame", "Spider-Man: Far From Home", "Black Widow",
    "Shang-Chi and the Legend of the Ten Rings", "Eternals",
    "Spider-Man: No Way Home", "Doctor Strange in the Multiverse of Madness",
    "Thor: Love and Thunder", "Black Panther: Wakanda Forever",
    "Ant-Man and the Wasp: Quantumania", "Guardians of the Galaxy Vol. 3",
    "The Marvels", "Deadpool & Wolverine", "Captain America: Brave New World",
    "Thunderbolts", "The Fantastic Four: First Steps","Spider-Man","Spider-Man 2",
    "Spider-Man 3","The Amazing Spider-Man","The Amazing Spider-Man2","Spider-Man: Across the Spider-Verse",
    "Spider-Man: Into the Spider-Verse",

    # X-Men Films (13)
    "X-Men", "X2: X-Men United", "X-Men: The Last Stand",
    "X-Men Origins: Wolverine", "X-Men: First Class", "The Wolverine",
    "X-Men: Days of Future Past", "Deadpool", "X-Men: Apocalypse",
    "Logan", "Deadpool 2", "The New Mutants", "X-Men: Dark Phoenix",

    # Harry Potter (8)
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Deathly Hallows – Part 1",
    "Harry Potter and the Deathly Hallows – Part 2",

    # Star Wars (12)
    "Star Wars: Episode IV – A New Hope",
    "Star Wars: Episode V – The Empire Strikes Back",
    "Star Wars: Episode VI – Return of the Jedi",
    "Star Wars: Episode I – The Phantom Menace",
    "Star Wars: Episode II – Attack of the Clones",
    "Star Wars: Episode III – Revenge of the Sith",
    "Star Wars: Episode VII – The Force Awakens",
    "Star Wars: Episode VIII – The Last Jedi",
    "Star Wars: Episode IX – The Rise of Skywalker",
    "Rogue One: A Star Wars Story",
    "Solo: A Star Wars Story",
    "Star Wars: The Clone Wars",

    # Lord of the Rings & Hobbit Films (7)
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Desolation of Smaug",
    "The Hobbit: The Battle of the Five Armies",
    "The Lord of the Rings: The Rings of Power",

    # Jurassic Park Franchise (6)
    "Jurassic Park",
    "The Lost World: Jurassic Park",
    "Jurassic Park III",
    "Jurassic World",
    "Jurassic World: Fallen Kingdom",
    "Jurassic World Dominion",

    # John Wick Films (4)
    "John Wick",
    "John Wick: Chapter 2",
    "John Wick: Chapter 3 – Parabellum",
    "John Wick: Chapter 4",

    # Transformers Movies (8)
    "Transformers",
    "Transformers: Revenge of the Fallen",
    "Transformers: Dark of the Moon",
    "Transformers: Age of Extinction",
    "Transformers: The Last Knight",
    "Bumblebee",
    "Transformers: Rise of the Beasts",
    "Transformers One",

    # Pirates of the Caribbean (5)
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Pirates of the Caribbean: At World's End",
    "Pirates of the Caribbean: On Stranger Tides",
    "Pirates of the Caribbean: Dead Men Tell No Tales",

    # Classic and Modern Films (56)
    "The Shawshank Redemption",
    "12 Angry Men",
    "Schindler's List",
    "Fight Club",
    "Forrest Gump",
    "The Matrix",
    "Good Will Hunting",
    "Eternal Sunshine of the Spotless Mind",
    "Requiem for a Dream",
    "Oldboy",
    "City Lights",
    "Grave of the Fireflies",
    "It's a Wonderful Life",
    "Toy Story",
    "Paths of Glory",
    "Modern Times",
    "The Lion King",
    "Rear Window",
    "Singin' in the Rain",
    "Raging Bull",
    "Psycho",
    "The Green Mile",
    "Cloud Atlas",
    "Black Swan",
    "The Hurt Locker",
    "The Imitation Game",
    "Se7en",
    "The Dark Knight Rises",
    "Once Upon a Time in Hollywood",
    "In the Mood for Love",
    "The Social Network",
    "Mad Max: Fury Road",
    "Pulp Fiction",
    "Interstellar",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "The Usual Suspects",
    "Vertigo",
    "The Prestige",
    "Memento",
    "Whiplash",
    "The Departed",
    "Gladiator",
    "Spirited Away",
    "Toy Story 3",
    "Finding Nemo",
    "WALL·E",
    "Up",
    "Inside Out",
    "Coco",
    "How to Train Your Dragon",
    "Princess Mononoke",
    "Your Name",
    "Dumbo",
    "Snow White and the Seven Dwarfs",
    "Spider-Man: Into the Spider-Verse",
    "The Wizard of Oz",
    "One Flew Over the Cuckoo's Nest",
    "Terminator 2: Judgment Day",
    "Aliens",
    "E.T. the Extra-Terrestrial",
    "Back to the Future",
    "The Good, the Bad and the Ugly",
    "Blade Runner",
    "Taxi Driver",
    "Amelie",
    
    # Classic Hollywood (10)
    "The Godfather",
    "The Godfather: Part II",
    "The Godfather: Part III",
    
    # Modern Blockbusters & Award Winners (15)
    "Inception",
    "The Dark Knight",
    "Parasite",
    "Everything Everywhere All at Once",
    "La La Land",
    "The Shape of Water",
    "The Grand Budapest Hotel",
    "Dune",
    "Dune: Part Two",
    "Oppenheimer",
    "Barbie",
    "Avatar",
    "Avatar: The Way of Water",
    "Titanic",
    "Jaws",
    
    # Popular Animated Films (10)
    "Shrek",
    "Shrek 2",
    "The Incredibles",
    "Ratatouille",
    "Monsters, Inc.",
    "Moana",
    "Frozen",
    "Frozen II",
    "Zootopia",
    "The Shining",
]
all_movies = list(dict.fromkeys(all_movies))
print(len(all_movies))